"""empty message

Revision ID: f0bddf077ca4
Revises: 
Create Date: 2020-12-05 23:18:28.067114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bddf077ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    op.drop_constraint('tasks_user_id_key', 'tasks', type_='unique')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_unique_constraint('tasks_user_id_key', 'tasks', ['user_id'])
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
